# Generated by Django 3.0.3 on 2023-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='profile',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
