# Generated by Django 3.0.3 on 2023-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_detail_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='hall',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
