# Generated by Django 3.0.3 on 2023-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_detail_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='hall',
            field=models.IntegerField(null=True),
        ),
    ]
