# Generated by Django 3.0.3 on 2023-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20230324_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minBidPrice',
            field=models.IntegerField(null=True),
        ),
    ]
